### ISSUE TITLE
운동 루틴 / 운동 도메인 정의 및 코드 구현

### ISSUE THREAD

**Issue by TwOneZero** [gajchaewon/health-diary-back#121]
# TODO
---
* [x] 운동 도메인에 따른 코드 구현
    => 일단 간단하게 운동 종류(이름), 설명만 저장하고 루틴과 연결하는 식으로 진행
    * 엔티티
    * 리포지토리
* [x] 루틴 도메인에 따른 코드 구현
    => **루틴을 생성할 때 운동 엔티티가 필요함**
    * 엔티티
    * 리포지토리
* [x] `@ManyToMany` 대신 ->중간테이블 생성해서 일대다 - 다대일 로 연결하기
    * 생성자를 자식의 setter 를 이용해서 제한한다.
